### ISSUE TITLE
"L" shaped display causes java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by mstram** [eisental/BasicCircuits#15]
This server is running Craftbukkit version git-Bukkit-1.0.1-R1-b1597jnks

***\* clicking on an "L" shaped (2 high x 10,10 (20 block total length) display  sign*\*  to activate it 

2012-01-03 15:35:07 [SEVERE] Could not pass event PLAYER_INTERACT to RedstoneChips
java.lang.ArrayIndexOutOfBoundsException: 1
    at org.tal.basiccircuits.display.detectDisplay(display.java:145)
    at org.tal.basiccircuits.display.init(display.java:53)
    at org.tal.redstonechips.circuit.Circuit.initCircuit(Circuit.java:129)
    at org.tal.redstonechips.CircuitManager.activateCircuit(CircuitManager.java:214)
    at org.tal.redstonechips.CircuitManager.checkForCircuit(CircuitManager.java:191)
    at org.tal.redstonechips.CircuitManager.checkForCircuit(CircuitManager.java:86)
    at org.tal.redstonechips.RCPlayerListener.onPlayerInteract(RCPlayerListener.java:48)
    at org.bukkit.plugin.java.JavaPluginLoader$11.execute(JavaPluginLoader.java:335)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:178)
    at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:266)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:593)
    at net.minecraft.server.Packet15Place.a(SourceFile:39)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:93)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:550)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by eisental** [comment]
Fixed

**Comment by mstram** [comment]
Did up upload the jar(s) ?

On 1/3/12, Tal Eisenberg
reply@reply.github.com
wrote:

**Comment by mstram** [comment]
Looks like you did :) ... I restarted the servr

**Comment by eisental** [comment]
yeah, I forgot to tell you.

On Tuesday, January 3, 2012, Mike Stramba <
reply@reply.github.com>
wrote:

> Looks like you did :) ... I restarted the servr
>

**Comment by mstram** [comment]
It's not working.

The "L" you created is saying "missing wool block at pixel 0,1"

The one I created (I moved the "hig" blue block down), is saying
"can't find origin wool block" and it's throwing an error ... I'll
grab the log and post it

On 1/3/12, Tal Eisenberg
reply@reply.github.com
wrote:

> yeah, I forgot to tell you.
> 
> On Tuesday, January 3, 2012, Mike Stramba <
> reply@reply.github.com>
> wrote:
> 
> > Looks like you did :) ... I restarted the servr
> >

**Comment by mstram** [comment]
Actually it's *your"  "L" that's throwing the error

**Comment by eisental** [comment]
Oh, sorry, I didn't do that yet. I uploaded the 1 line and fixed some bugs.

On Tuesday, January 3, 2012, Mike Stramba <
reply@reply.github.com>
wrote:

> It's not working.
> 
> The "L" you created is saying "missing wool block at pixel 0,1"
> 
> The one I created (I moved the "hig" blue block down), is saying
> "can't find origin wool block" and it's throwing an error ... I'll
> grab the log and post it
> 
> On 1/3/12, Tal Eisenberg
> reply@reply.github.com
> wrote:
> 
> > yeah, I forgot to tell you.
> > 
> > On Tuesday, January 3, 2012, Mike Stramba <
> > reply@reply.github.com>
> > wrote:
> > 
> > > Looks like you did :) ... I restarted the servr
> > >

**Comment by mstram** [comment]
Ok, so it's the "vertical one" that should work ? .... Will test

**Comment by eisental** [comment]
can u restart? i reuploaded BC.

On Tuesday, January 3, 2012, Mike Stramba <
reply@reply.github.com>
wrote:

**Comment by mstram** [comment]
Works great .

Now ... what about supporting "multi bends" ?  (I.e.  a box ....or "snake" ?)

Not a big priority ... just an idea :)

On 1/3/12, Tal Eisenberg
reply@reply.github.com
wrote:

**Comment by eisental** [comment]
it will be very complicated to make it work in 3d (when not both corners
are on one plane), but who knows...

On Wednesday, January 4, 2012, Mike Stramba <
reply@reply.github.com>
wrote:

**Comment by mstram** [comment]
> it will be very complicated to make it work in 3d (when not both corners
> are on one plane), but who knows.

I was just thinking one plane for now ("circuit board" wiring)

On 1/4/12, Tal Eisenberg
reply@reply.github.com
wrote:

**Comment by eisental** [comment]
You can make it any shape u like on one plane. You just have to figure out
the coordinates for the pixels.
A 2d "snake" is considered a rectangle screen with missing wool blocks.

On Wed, Jan 4, 2012 at 3:01 PM, Mike Stramba <
reply@reply.github.com

**Comment by mstram** [comment]
> You can make it any shape u like on one plane. You just have to figure out
> the coordinates for the pixels.

Hmm, I tried an open ended square.

When I activated it it said it was something like  2 blocks by 0 or
someting weird   showing 2 bits for X .. Y was not mentioned at all

.. I didn't try to actually run it   / hook up a transmitter....

Will do that ... .... next :)

On 1/4/12, Tal Eisenberg
reply@reply.github.com
wrote:
